input FarcasterUserClaimTransactionDetailsInput {
  fid: Int!
  transactionId: String
}

type FarcasterUserClaimTransactionDetails {
  fid: ID!
  availableClaimAmount: Float!
  minimumClaimableAmountInWei: String!
  availableClaimAmountInWei: String!
  claimedAmount: Float!
  claimedAmountInWei: String!
  processingAmount: Float!
  processingAmountInWei: String!
}

type Query {
  FarcasterUserClaimTransactionDetails(
    input: FarcasterUserClaimTransactionDetailsInput!
  ): FarcasterUserClaimTransactionDetails
}
